# Streamlit Secrets Configuration
# This file contains configuration secrets for the Streamlit UI

[api]
API_URL = "http://localhost:8000/api/v1"

[app]
title = "Project Polaris - Document Intelligence"
description = "AI-powered document analysis and summarization platform"